version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  weatherapi:
    build: ./src/Weather.API
    ports:
      - "5001:80"
  locationapi:
    build: ./src/Location.API
    ports:
      - "5002:80"